function [target,time,Gqw,Gqx,Gqy,Gqz,Lqw,Lqx,Lqy,Lqz,rx,ry,rz,lx,ly,lz,ax,ay,az,mx,my,mz,gx,gy,gz] = importtripodmap(workbookFile,sheetName,startRow,endRow)
%IMPORTFILE Import data from a spreadsheet
%   [target,time,Gqw,Gqx,Gqy,Gqz,Lqw,Lqx,Lqy,Lqz,rx,ry,rz,lx,ly,lz,ax,ay,az,mx,my,mz,gx,gy,gz]
%   = IMPORTFILE(FILE) reads data from the first worksheet in the Microsoft
%   Excel spreadsheet file named FILE and returns the data as column
%   vectors.
%
%   [target,time,Gqw,Gqx,Gqy,Gqz,Lqw,Lqx,Lqy,Lqz,rx,ry,rz,lx,ly,lz,ax,ay,az,mx,my,mz,gx,gy,gz]
%   = IMPORTFILE(FILE,SHEET) reads from the specified worksheet.
%
%   [target,time,Gqw,Gqx,Gqy,Gqz,Lqw,Lqx,Lqy,Lqz,rx,ry,rz,lx,ly,lz,ax,ay,az,mx,my,mz,gx,gy,gz]
%   = IMPORTFILE(FILE,SHEET,STARTROW,ENDROW) reads from the specified
%   worksheet for the specified row interval(s). Specify STARTROW and
%   ENDROW as a pair of scalars or vectors of matching size for
%   dis-contiguous row intervals. To read to the end of the file specify an
%   ENDROW of inf.
%
%	Non-numeric cells are replaced with: NaN
%
% Example:
%   [target,time,Gqw,Gqx,Gqy,Gqz,Lqw,Lqx,Lqy,Lqz,rx,ry,rz,lx,ly,lz,ax,ay,az,mx,my,mz,gx,gy,gz]
%   = importfile('tripod17chop.xlsx','tripod17chop',1,8936);
%
%   See also XLSREAD.

% Auto-generated by MATLAB on 2014/03/21 10:45:24

%% Input handling

% If no sheet is specified, read first sheet
if nargin == 1 || isempty(sheetName)
    sheetName = 1;
end

% If row start and end points are not specified, define defaults
if nargin <= 3
    startRow = 1;
    endRow = 8936;
end

%% Import the data
[~, ~, raw] = xlsread(workbookFile, sheetName, sprintf('A%d:Y%d',startRow(1),endRow(1)));
for block=2:length(startRow)
    [~, ~, tmpRawBlock] = xlsread(workbookFile, sheetName, sprintf('A%d:Y%d',startRow(block),endRow(block)));
    raw = [raw;tmpRawBlock]; %#ok<AGROW>
end
raw(cellfun(@(x) ~isempty(x) && isnumeric(x) && isnan(x),raw)) = {''};

%% Replace non-numeric cells with NaN
R = cellfun(@(x) ~isnumeric(x) && ~islogical(x),raw); % Find non-numeric cells
raw(R) = {NaN}; % Replace non-numeric cells

%% Create output variable
data = reshape([raw{:}],size(raw));

%% Allocate imported array to column variable names
target = data(:,1);
time = data(:,2);
Gqw = data(:,3);
Gqx = data(:,4);
Gqy = data(:,5);
Gqz = data(:,6);
Lqw = data(:,7);
Lqx = data(:,8);
Lqy = data(:,9);
Lqz = data(:,10);
rx = data(:,11);
ry = data(:,12);
rz = data(:,13);
lx = data(:,14);
ly = data(:,15);
lz = data(:,16);
ax = data(:,17);
ay = data(:,18);
az = data(:,19);
mx = data(:,20);
my = data(:,21);
mz = data(:,22);
gx = data(:,23);
gy = data(:,24);
gz = data(:,25);

