function [tQw,tQx,tQy,tQz,t,GQw,GQx,GQy,GQz,Lqw,Lqx,Lqy,Lqz,rx,ry,rz,lx,ly,lz,ax,ay,az,mx,my,mz,gs,gy,gz] = importtripodmapQ(workbookFile,sheetName,startRow,endRow)
%IMPORTFILE Import data from a spreadsheet
%   [tQw,tQx,tQy,tQz,t,GQw,GQx,GQy,GQz,Lqw,Lqx,Lqy,Lqz,rx,ry,rz,lx,ly,lz,ax,ay,az,mx,my,mz,gx,gy,gz]
%   = IMPORTFILE(FILE) reads data from the first worksheet in the Microsoft
%   Excel spreadsheet file named FILE and returns the data as column
%   vectors.
%
%   [tQw,tQx,tQy,tQz,t,GQw,GQx,GQy,GQz,Lqx,Lqy,Lqz,rx,ry,rz,lx,ly,lz,ax,ay,az,mx,my,mz,gx,gy,gz]
%   = IMPORTFILE(FILE,SHEET) reads from the specified worksheet.
%
%   [tQw,tQx,tQy,tQz,t,GQw,GQx,GQy,GQz,Lqx,Lqy,Lqz,rx,ry,rz,lx,ly,lz,ax,ay,az,mx,my,mz,gx,gy,gz]
%   = IMPORTFILE(FILE,SHEET,STARTROW,ENDROW) reads from the specified
%   worksheet for the specified row interval(s). Specify STARTROW and
%   ENDROW as a pair of scalars or vectors of matching size for
%   dis-contiguous row intervals. To read to the end of the file specify an
%   ENDROW of inf.
%
%	Non-numeric cells are replaced with: NaN
%
% Example:
%   [tQw,tQx,tQy,tQz,t,GQw,GQx,GQy,GQz,Lqx,Lqy,Lqz,rx,ry,rz,lx,ly,lz,ax,ay,az,mx,my,mz,gx,gy,gz]
%   = importfile('tripod31chop.xlsx','testQ',1,14745);
%
%   See also XLSREAD.

% Auto-generated by MATLAB on 2014/05/13 15:49:29

%% Input handling

% If no sheet is specified, read first sheet
if nargin == 1 || isempty(sheetName)
    sheetName = 1;
end

% If row start and end points are not specified, define defaults
if nargin <= 3
    startRow = 1;
    endRow = 14745;
end

%% Import the data
[~, ~, raw] = xlsread(workbookFile, sheetName, sprintf('A%d:AB%d',startRow(1),endRow(1)));
for block=2:length(startRow)
    [~, ~, tmpRawBlock] = xlsread(workbookFile, sheetName, sprintf('A%d:AB%d',startRow(block),endRow(block)));
    raw = [raw;tmpRawBlock]; %#ok<AGROW>
end
raw(cellfun(@(x) ~isempty(x) && isnumeric(x) && isnan(x),raw)) = {''};

%% Replace non-numeric cells with NaN
R = cellfun(@(x) ~isnumeric(x) && ~islogical(x),raw); % Find non-numeric cells
raw(R) = {NaN}; % Replace non-numeric cells

%% Create output variable
data = reshape([raw{:}],size(raw));

%% Allocate imported array to column variable names
tQw = data(:,1);
tQx = data(:,2);
tQy = data(:,3);
tQz = data(:,4);
t = data(:,5);
GQw = data(:,6);
GQx = data(:,7);
GQy = data(:,8);
GQz = data(:,9);
Lqw = data(:,10);
Lqx = data(:,11);
Lqy = data(:,12);
Lqz = data(:,13);
rx = data(:,14);
ry = data(:,15);
rz = data(:,16);
lx = data(:,17);
ly = data(:,18);
lz = data(:,19);
ax = data(:,20);
ay = data(:,21);
az = data(:,22);
mx = data(:,23);
my = data(:,24);
mz = data(:,25);
gs = data(:,26);
gy = data(:,27);
gz = data(:,28);

