function [time,ax1,ay1,az1,mx1,my1,mz1,ax2,ay2,az2,mx2,my2,mz2,ax3,ay3,az3,mx3,my3,mz3,ax4,ay4,az4,mx4,my4,mz4,ax5,ay5,az5,mx5,my5,mz5,ax0,ay0,az0,mx0,my0,mz0] = importfileSept(filename, startRow, endRow)
%IMPORTFILE Import numeric data from a text file as column vectors.
%   [TIME,AX1,AY1,AZ1,MX1,MY1,MZ1,AX2,AY2,AZ2,MX2,MY2,MZ2,AX3,AY3,AZ3,MX3,MY3,MZ3,AX4,AY4,AZ4,MX4,MY4,MZ4,AX5,AY5,AZ5,MX5,MY5,MZ5,AX0,AY0,AZ0,MX0,MY0,MZ0]
%   = IMPORTFILE(FILENAME) Reads data from text file FILENAME for the
%   default selection.
%
%   [TIME,AX1,AY1,AZ1,MX1,MY1,MZ1,AX2,AY2,AZ2,MX2,MY2,MZ2,AX3,AY3,AZ3,MX3,MY3,MZ3,AX4,AY4,AZ4,MX4,MY4,MZ4,AX5,AY5,AZ5,MX5,MY5,MZ5,AX0,AY0,AZ0,MX0,MY0,MZ0]
%   = IMPORTFILE(FILENAME, STARTROW, ENDROW) Reads data from rows STARTROW
%   through ENDROW of text file FILENAME.
%
% Example:
%   [time,ax1,ay1,az1,mx1,my1,mz1,ax2,ay2,az2,mx2,my2,mz2,ax3,ay3,az3,mx3,my3,mz3,ax4,ay4,az4,mx4,my4,mz4,ax5,ay5,az5,mx5,my5,mz5,ax0,ay0,az0,mx0,my0,mz0]
%   = importfile('beam-7mm4.csv',2, 1131);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2015/02/04 15:23:47

%% Initialize variables.
delimiter = ',';
if nargin<=2
    startRow = 2;
    endRow = inf;
end

%% Format string for each line of text:
%   column1: double (%f)
%	column16: double (%f)
%   column17: double (%f)
%	column18: double (%f)
%   column19: double (%f)
%	column20: double (%f)
%   column21: double (%f)
%	column41: double (%f)
%   column42: double (%f)
%	column43: double (%f)
%   column44: double (%f)
%	column45: double (%f)
%   column46: double (%f)
%	column66: double (%f)
%   column67: double (%f)
%	column68: double (%f)
%   column69: double (%f)
%	column70: double (%f)
%   column71: double (%f)
%	column91: double (%f)
%   column92: double (%f)
%	column93: double (%f)
%   column94: double (%f)
%	column95: double (%f)
%   column96: double (%f)
%	column116: double (%f)
%   column117: double (%f)
%	column118: double (%f)
%   column119: double (%f)
%	column120: double (%f)
%   column121: double (%f)
%	column141: double (%f)
%   column142: double (%f)
%	column143: double (%f)
%   column144: double (%f)
%	column145: double (%f)
%   column146: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%f%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%f%f%f%f%f%f%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%f%f%f%f%f%f%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%f%f%f%f%f%f%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%f%f%f%f%f%f%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%f%f%f%f%f%f%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%f%f%f%f%f%f%*s%*s%*s%*s%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'EmptyValue' ,NaN,'HeaderLines', startRow(1)-1, 'ReturnOnError', false);
for block=2:length(startRow)
    frewind(fileID);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'EmptyValue' ,NaN,'HeaderLines', startRow(block)-1, 'ReturnOnError', false);
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Allocate imported array to column variable names
time = dataArray{:, 1};
ax1 = dataArray{:, 2};
ay1 = dataArray{:, 3};
az1 = dataArray{:, 4};
mx1 = dataArray{:, 5};
my1 = dataArray{:, 6};
mz1 = dataArray{:, 7};
ax2 = dataArray{:, 8};
ay2 = dataArray{:, 9};
az2 = dataArray{:, 10};
mx2 = dataArray{:, 11};
my2 = dataArray{:, 12};
mz2 = dataArray{:, 13};
ax3 = dataArray{:, 14};
ay3 = dataArray{:, 15};
az3 = dataArray{:, 16};
mx3 = dataArray{:, 17};
my3 = dataArray{:, 18};
mz3 = dataArray{:, 19};
ax4 = dataArray{:, 20};
ay4 = dataArray{:, 21};
az4 = dataArray{:, 22};
mx4 = dataArray{:, 23};
my4 = dataArray{:, 24};
mz4 = dataArray{:, 25};
ax5 = dataArray{:, 26};
ay5 = dataArray{:, 27};
az5 = dataArray{:, 28};
mx5 = dataArray{:, 29};
my5 = dataArray{:, 30};
mz5 = dataArray{:, 31};
ax0 = dataArray{:, 32};
ay0 = dataArray{:, 33};
az0 = dataArray{:, 34};
mx0 = dataArray{:, 35};
my0 = dataArray{:, 36};
mz0 = dataArray{:, 37};


