function [time,Gqw,Gqx,Gqy,Gqz,Lqw,Lqx,Lqy,Lqz,rx,ry,rz,lx,ly,lz,ax,ay,az,mx,my,mz,gx,gy,gz,temp] = importusb(filename, startRow, endRow)
%IMPORTFILE Import numeric data from a text file as column vectors.
%   [TIME,GQW,GQX,GQY,GQZ,LQW,LQX,LQY,LQZ,RX,RY,RZ,LX,LY,LZ,AX,AY,AZ,MX,MY,MZ,GX,GY,GZ,TEMP]
%   = IMPORTFILE(FILENAME) Reads data from text file FILENAME for the
%   default selection.
%
%   [TIME,GQW,GQX,GQY,GQZ,LQW,LQX,LQY,LQZ,RX,RY,RZ,LX,LY,LZ,AX,AY,AZ,MX,MY,MZ,GX,GY,GZ,TEMP]
%   = IMPORTFILE(FILENAME, STARTROW, ENDROW) Reads data from rows STARTROW
%   through ENDROW of text file FILENAME.
%
% Example:
%   [time,Gqw,Gqx,Gqy,Gqz,Lqw,Lqx,Lqy,Lqz,rx,ry,rz,lx,ly,lz,ax,ay,az,mx,my,mz,gx,gy,gz,temp]
%   = importfile('tripod16.csv',2, 20842);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2014/02/18 14:51:47

%% Initialize variables.
delimiter = ',';
if nargin<=2
    startRow = 2;
    endRow = inf;
end

%% Format string for each line of text:
%   column1: double (%f)
%	column2: double (%f)
%   column3: double (%f)
%	column4: double (%f)
%   column5: double (%f)
%	column6: double (%f)
%   column7: double (%f)
%	column8: double (%f)
%   column9: double (%f)
%	column10: double (%f)
%   column11: double (%f)
%	column12: double (%f)
%   column13: double (%f)
%	column14: double (%f)
%   column15: double (%f)
%	column16: double (%f)
%   column17: double (%f)
%	column18: double (%f)
%   column19: double (%f)
%	column20: double (%f)
%   column21: double (%f)
%	column22: double (%f)
%   column23: double (%f)
%	column24: double (%f)
%   column25: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'EmptyValue' ,NaN,'HeaderLines', startRow(1)-1, 'ReturnOnError', false);
for block=2:length(startRow)
    frewind(fileID);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'EmptyValue' ,NaN,'HeaderLines', startRow(block)-1, 'ReturnOnError', false);
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Allocate imported array to column variable names
time = dataArray{:, 1};
Gqw = dataArray{:, 2};
Gqx = dataArray{:, 3};
Gqy = dataArray{:, 4};
Gqz = dataArray{:, 5};
Lqw = dataArray{:, 6};
Lqx = dataArray{:, 7};
Lqy = dataArray{:, 8};
Lqz = dataArray{:, 9};
rx = dataArray{:, 10};
ry = dataArray{:, 11};
rz = dataArray{:, 12};
lx = dataArray{:, 13};
ly = dataArray{:, 14};
lz = dataArray{:, 15};
ax = dataArray{:, 16};
ay = dataArray{:, 17};
az = dataArray{:, 18};
mx = dataArray{:, 19};
my = dataArray{:, 20};
mz = dataArray{:, 21};
gx = dataArray{:, 22};
gy = dataArray{:, 23};
gz = dataArray{:, 24};
temp = dataArray{:, 25};

