function plotpp(filename)
% create plots from post-processed data produced by
% mems_Kalman_postprocess.m

[time,EqKm_x,EqKm_y,EqKm_z,Sens_x,Sens_y,Sens_z,a_x,a_y,a_z,m_x,m_y,m_z,...
    g_x,g_y,g_z,Km_g_x,Km_g_y,Km_g_z,qKm_w,qKm_x,qKm_y,qKm_z,J] ...
    = importpp(filename);

% compare elevation angles generated by instantaneous sensor readings (FQA)
% with Kalman filter output
% figure
% plot(time,Sens_y*180/pi,'Color',[.6 .6 .6])
% % ax = gca;
% % ax.FontSize = 14;
% hold on; plot(time,EqKm_y*180/pi,'k','LineWidth',2)
% legend('FQA','EKF','location','southeast')
% xlabel('Time (s)')
% ylabel('Elevation Angle (deg)          .')
% % title(filename)
% xlim([2 12])
% 
% figure
% plot(time,Sens_x*180/pi,'Color',[.6 .6 .6])
% % ax = gca;
% % ax.FontSize = 14;
% hold on; plot(time,EqKm_x*180/pi,'k','LineWidth',2)
% legend('FQA','EKF','location','southeast')
% xlabel('Time (s)')
% % ylabel('Elevation Angle (deg)')
% ylabel('Roll Angle (deg)')
% % title(filename)
% 
% figure
% plot(time,Sens_y*180/pi,'Color',[.6 .6 .6])
% hold on; plot(time,EqKm_y*180/pi,'k','LineWidth',2)
% legend('FQA','EKF','location','southeast')
% xlabel('Time (s)')
% ylabel('Elevation Angle (deg)')
% 
% figure
% plot(time,Sens_z*180/pi,'Color',[.6 .6 .6])
% hold on; plot(time,EqKm_z*180/pi,'k','LineWidth',2)
% legend('FQA','EKF','location','southeast')
% xlabel('Time (s)')
% ylabel('Heading (deg)')
% 
% figure
% plot(time,Sens_x*180/pi,'Color',[.8 .8 .8])
% hold on; plot(time,EqKm_x*180/pi,'-.k','LineWidth',1)
% plot(time,Sens_y*180/pi,'Color',[.6 .6 .6])
% plot(time,EqKm_y*180/pi,'k','LineWidth',2)
% % plot(time,Sens_z*180/pi,'Color',[.8 .8 .8])
% % plot(time,EqKm_z*180/pi,'-.k','LineWidth',1)
% legend('Roll FQA','Roll EKF','Elevation FQA','Elevation EKF',...
%     'location','southeast')
% xlabel('Time (s)')
% ylabel('Rotation angle (deg)')

figure
plot(time,Sens_x*180/pi)
hold on; plot(time,EqKm_x*180/pi,'LineWidth',2)
plot(time,Sens_y*180/pi)
plot(time,EqKm_y*180/pi,'LineWidth',2)
plot(time,Sens_z*180/pi)
plot(time,EqKm_z*180/pi,'LineWidth',1)
legend('Roll FQA','Roll EKF','Elevation FQA','Elevation EKF',...
    'Heading FQA','Heading EKF',...
    'location','northwest')
xlabel('Time (s)')
ylabel('Rotation angle (deg)')

% figure
% plot(time,EqKm_x*180/pi,'k')
% hold on
% plot(time,EqKm_y*180/pi,'k','LineWidth',2)
% plot(time,EqKm_z*180/pi,'Color',[.6 .6 .6])
% legend('Roll','Elevation','Heading','location','northwest')
% xlabel('Time (s)')
% ylabel('Rotation angle (deg)')
% xlim([0 180])